# This is placeholder content. Contact selfhosted@ruddervirt.com to obtain your credentials
apiVersion: v1
kind: Secret
metadata:
  name: modules-auth
  namespace: default
type: Opaque
stringData:
  authorization: factorydefault
