# This is placeholder content. Contact selfhosted@ruddervirt.com to obtain your credentials
apiVersion: v1
kind: Secret
metadata:
  namespace: default
  name: ghcr-pull-secret
data:
  .dockerconfigjson: "e30"
type: kubernetes.io/dockerconfigjson