apiVersion: kubevirt.io/v1
kind: KubeVirt
metadata:
  name: kubevirt
  namespace: kubevirt
spec:
  configuration:
    developerConfiguration:
      featureGates:
        - DataVolumes
        - Sidecar
        - VMPersistentState
        - Snapshot
---
apiVersion: cdi.kubevirt.io/v1beta1
kind: CDI
metadata:
  name: cdi
spec:
  config:
    podResourceRequirements:
      limits:
        cpu: "4"
        memory: "2Gi"
      requests:
        cpu: "2"
        memory: "1Gi"
    featureGates: []
